server:
  port: 80
  servlet:
    context-path: /


#thymeleaf模板
spring:
  aop:
    auto: true #启动aop配置
  thymeleaf:
    cache: true
    prefix:
      classpath: /templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  #数据连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.77:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 838061522

  # mybatis 配置
mybatis:
  mapper-locations: classpath:mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true #驼峰转换
    use-generated-keys: true #获取数据库自增列
    use-column-label: true #使用列别名替换列名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

